# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [3]:
s="Hi there Sam!"
x=s.split()
print(x)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [2]:
planet="Earth"
diameter=12742
print("The diameter of{} is {} kilometers.".format(planet,diameter))

The diameter ofEarth is 12742 kilometers.


bold text## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [4]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]['target'][3])

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [6]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [7]:
import numpy as np
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


## 5. Create an array of all the even integers from 20 to 35

In [8]:
import numpy as np
array=np.arange(20,36,2)
print("array of all the even integers from 20 o 35 ")
print(array)

array of all the even integers from 20 o 35 
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [9]:
import numpy as np
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [10]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.concatenate((a,b),axis=0)
print(c)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [11]:
import pandas as pd
data=[['anu',21],['dia,18'],['dev',36]]
df=pd.DataFrame(data,columns=['Name','Age'])
print(df)

     Name   Age
0     anu  21.0
1  dia,18   NaN
2     dev  36.0


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [13]:
import datetime
start=datetime.date(2023,1,1)
k=41
res=[]
for day in range(k):
  date=(start+datetime.timedelta(days=day)).isoformat()
  res.append(date)
  print("Next K dates list:"+str(res))

Next K dates list:['2023-01-01']
Next K dates list:['2023-01-01', '2023-01-02']
Next K dates list:['2023-01-01', '2023-01-02', '2023-01-03']
Next K dates list:['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04']
Next K dates list:['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04', '2023-01-05']
Next K dates list:['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04', '2023-01-05', '2023-01-06']
Next K dates list:['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04', '2023-01-05', '2023-01-06', '2023-01-07']
Next K dates list:['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04', '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08']
Next K dates list:['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04', '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08', '2023-01-09']
Next K dates list:['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04', '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08', '2023-01-09', '2023-01-10']
Next K dates list:['2023-01-01', '2023-0

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [ ]:
import pandas as pd
lists=[[1,'aaa',22],[2,'bbb',25],[3,'ccc',24]]
df=pd.DataFrame(lists,columns=['column1','column2','column3'],dtype=int)
print